### ISSUE TITLE
Excuse me,Can this library use in web application?

### ISSUE THREAD

**Issue by yuwochangzai** [traf72/excel-report-generator#1]
I see "Assembly.GetEntryAssembly()" in DefaultTypeProvider.cs,but it return null in my webapi application.

**Comment by traf72** [comment]
Hello!

Yes, you can use this library in a web application. The constructor of this class can take a collection of assemblies which will be used to search types. You can read how to extend DefaultTypeProvider in the section "**Connection and extension**" chapter "**3. Extension of DefaultTypeProvider**" .

**Comment by yuwochangzai** [comment]
OK,Thank you.
