### ISSUE TITLE
How can I set predicate for column?

### ISSUE THREAD

**Issue by iRumba** [traf72/excel-report-generator#2]
I want to filter data items by predicate. I tried set native excel filter on columns, but i need date filter for date values etc. Because column template configuration follows after column name, excel offers text filter.

How can i configure ExcelReportGenerator for filtering output data by predicate?

**Comment by traf72** [comment]
Hello!

If you want to render all data to Excel at first and then filter data in any column, you can use the standard Excel filter. ExcelReportGenerator preserves data types in columns.

If you want to filter data before render them to Excel, you can create the parameter for this purpose in you report class. Then you can set this parameter from your code and filter your data source according to the parameter.

ExcelReportGenerator does not support predicates in Excel templates.
